# Generated by Django 4.1.7 on 2023-08-01 17:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('certificate_generation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('certificate_award_date', models.DateField()),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_generator_app.certificate')),
            ],
        ),
    ]
