# Generated by Django 4.1.7 on 2023-08-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_generator_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatedetails',
            old_name='certificate',
            new_name='certificate_id',
        ),
    ]
